### ISSUE TITLE
Figma integration 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/design-gc-conception#101]
**TODO**

- [ ] Review current GC Design system Figma files (CRA, ESDC, etc) 
- [x] Review Notify's and COVID Alerts Figma file workflow and format 
- [x] Walk through the existing workflow to see where we can leverage formatting opportunities
- [ ] Log the gaps, opportunities, and risk of using Figma in this way  
- [ ] Share at Product Pod meeting and ds-general for review and feedback 
- [ ] Iterate on feedback 
- [ ] Share with @catalinaperezn  to plan usability and workflow research goals 
  

**Outcomes**
- Understand what Figma formats currently exist for the GC Design system 
- Understand what current features and plugins are lean and support design systems at scale 
- Understand the risks of using Figma 
- Exploration of how we can describe and format design tokens and components for desired implementation 
- Create a Figma file format *prototype* to test with small teams who use the design system to create web products, to better assess and understand the gaps in the developer and designer implementation workflow. 

**Deliverables**
- List of Figma integration gaps, opportunities, risks 
- Next iteration of the Figma file @delisma started for the design tokens 
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
- Way-finding and naming 
- Components that do not represent the basic UI lvl listed in the roadmap

**Comment by delisma** [comment]
Need to align the input and output workflow of tokens in Figma and Style Dictionary.
GitHub
   |_ output files
      |_ Figma
      |_ Style Dictionary
  |_ input tokens
      |_ Figma
      |_ Style Dictionary

Thinking of separate tokens into core, utilities and component tokens and having some explicit and implicite rules around the classification. Following Josh architecture model.

- Core has the raw values
- Utilities has no raw values, consume the core tokens only
- Component has no raw or core values, consume the utilities tokens only

Integrating a token documentation into the Figma file from the description field of the token. Leveraging Figma Tokens plugins to document:
- values/raw values
- token names
- description

**Comment by samsadasivan** [comment]
Phil to help with the logging the gaps and opportunities of using Figma as a touchpoint for others to reference and for a DS product team to update and scale overtime

https://philippecaron.notion.site/Figma-for-DS-1a1118dee54747a69445c46581c7596f

**Comment by samsadasivan** [comment]
UPDATE 

- Align on approach for visual language within the tokens
- Align on workflow, @nmakuch to document the process in a map in the [Drafting Data Figma file](https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/Drafting-data?node-id=230%3A2) 
- Start (or continue) in another Figma file to import token values to create the Component page wireframe for the button work (connected to v1. Component Page card) 
- @samsadasivan to document the risks and opportunities of FIGMA as a touchpoint and a process 
- @SmartMouthWords to curate content to describe the FIGMA touchpoint tool and function within the DS

**Comment by samsadasivan** [comment]
**Tool description:** 
Figma is a vector graphics editor and prototyping tool which is primarily web-based, with additional offline features enabled by desktop applications.  
Design system context:  
The Figma pages of visuals and content to make design decisions that inline with policies related to: 

Identity and brand (communications policy)  
UX (product team) 
Accessibility and bilingualism (product policy) 

The tokens will be integrated via the figma token plugin and will keep certain visual attributes of the component 

Figma is a working tool with specific visual identity and tone for Canada.ca, accessibility standards, and French content design. The file will be using the Tokens plugin, component vector design, and rationale to build pages quickly using the web tool. This file will stay updated with new iterations and rationale as the system evolves. 


**Risks**

Maintenance - This file will get messy. It will be up to CDS to keep it up to date and inline with other documentation in the system. Building a library won’t happen on the first try, maybe not even the second. Note: Cross-referencing other libraries in the Figma community and other products will help influence the scaling of Figma.   ”Each time we fail, we learn something new. So far I’ve built many component libraries for as many projects. All were totally useful and definitely not a waste of time: Because I used them as a working tool. A tool that enabled me to prototype rapidly, and share ideas within the team.” — Phil Caron

Versioning - Manual versioning and archiving of components will need to have a formal process. Archiving is not a recommended for Figma. 

Export - 



**Opportunities:**
Flexibility - 
Baked in accessibility - 
Manage components in atoms -
