### ISSUE TITLE
Prepare for React SSR canary release

### ISSUE THREAD

**Issue by daine** [cds-snc/design-gc-conception#1010]
## 📇 Task
[Prepwork for React SSR canary release plan
](https://docs.google.com/document/d/14TwlBuSd01zNkF7srl8cL1KWP0dlMvWEiDZlrbY0F6c/edit)

Version the react-ssr and tag it as a canary release. Test a dry-run on npm

## ✅ Definition of Done / Outcomes
- [x] Done when `packages/react-ssr/package.json` is updated with a canary version
- [x] Done when we're confident that publishing the package on npm will be successfull

## 📜 Acceptance criteria
- [x] Version number has the tag `canary.x` appended to it
- [x] A `dry-run` of publish has been tested
- [x] A test publish of the package (followed by installation) has been achieved.

## 📝 More info
`npm version prerelease --preid=canary` should take care of the versioning 
`npm publish --dry-run --tag canary` will add the canary tag to the package

**Comment by daine** [comment]
All items completed, and the updates are in this PR: https://github.com/cds-snc/gcds-components/pull/587
