### ISSUE TITLE
Buttons and links (M)

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/design-gc-conception#102]
**TODO**
- [ ] Agree on requirements
- [ ] 

**Outcomes**
- Understanding the design variants, do's and don't, design specifications, accessibility approach, and the mandatory aspects of a button component 
- Begin to explore patterns in the way we break down a component. #waysofworking

**Deliverables**
- Figma file - drafting 
- Demo in HTML 
- [Requirements list](https://docs.google.com/document/d/17_ybsWqqg-LEqjjmVIvt5QxiyKEuPjMdgYwc-fwztEU/edit?usp=sharing) for a button component (it will also serve as a template for other components) 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
- Naming components

**Comment by samsadasivan** [comment]
I spoke with Ioana on what we should consider for the first pass for a button:
- Colour, typography, margins, padding
- Cross-platform states/ media queries (mobile, tablet, desktop)
- Focus states, active states (probably no hover or disabled for accessibility reasons but we can state that as well)
- HTML & CSS
- Annotated with do's and don'ts (stretch)
- Annotated with accessibility considerations (stretch)
- Annotated with communication and identity policy considerations (stretch)

**Comment by jmealing** [comment]
Adding the current work existing on buttons for reference

Live site: https://design.canada.ca/common-design-patterns/buttons.html
Raw work from DTO 2ish years ago: https://design.canada.ca/components/buttons.html

**Comment by jmealing** [comment]
@JoshBeveridge 
Requirement list draft:
https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/Drafting-data?node-id=476%3A2

**Comment by ioanacontu** [comment]
@SmartMouthWords to add the research done on button component.

**Comment by jmealing** [comment]
Comparison sheet of what we need/what current pages have: https://docs.google.com/spreadsheets/d/1pYR7OYa5A0585ioqTBCUQjRR0YSBWBh4GLJMJkt3fTo/edit#gid=0

**Comment by JoshBeveridge** [comment]
@ethanWallace and I are going to focus on getting a working version of the button component to a state where we feel it can be used by others. To that effect:
- Ethan's going to work on the back-end functionality of the button and how it accepts tasks and returns a callback
- I'm going to prep a list of styles and the subsequently create a list of control options to better define what we want end-users of the system to be able to modify vs. what is static, along with design reasoning

Once these are complete, we're going to reconvene to determine how we write the styling decisions into code

**Comment by SmartMouthWords** [comment]
I've been working on drafting button content here: https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/Drafting-data?node-id=816%3A26

**Comment by LPipes4** [comment]
We've created a co-task card for a working session to make some decisions related to this card. #109

**Comment by ioanacontu** [comment]
The items in this task left to do are covered in a separate epic.
