### ISSUE TITLE
Develop basic button component functionality 

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#110]
Finish work started on developing the gcds-button component to reach a functional base without styles. 

**TODO**
- [ ] Build basic style API from requirements doc 
- [ ] Update automated tests

**Outcomes**
- gcds-button will have base functionality with no defined styles

**Deliverables**
- gc-ds-button repo main branch updated with unstyled version of gcds-button.

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
- Styling gcds-button component

**Comment by ethanWallace** [comment]
Opened a pull request on gc-ds-button repo to review basic button functionality.

https://github.com/JoshBeveridge/gc-ds-button/pull/3
