### ISSUE TITLE
Publish: Basic page template and template overview page

### ISSUE THREAD

**Issue by daine** [cds-snc/design-gc-conception#1132]
## 📇 User story
Publish the pieces needed for basic page template

### Design 
- [x] [EN Figma template](https://www.figma.com/design/T0T9vUC8DghZEkP29X6ui3/Basic-Page-Template?node-id=33044-1756&t=619U7pjpdjZx7axM-4) is merged
- [x] [FR Figma template](https://www.figma.com/design/84sAFVNJVjcLXWPMKrbJwi/Page-de-base?node-id=3268-221790&t=YMDxfZqEldhbtGFH-4) is merged

### Content
- [x] Done when content for the documentation, design and code templates has been approved

### Development
- [x] Done when development has merged the basic page template PR in github

### Documentation
- [x] Done when designs (EN and FR) has been published, with the links updated on the documentation website
- [x] Done when code templates (EN and FR) have been published, with the links updated on the documentation website
- [x] Done when documentation has been published on the website (basic page template and template overview pages)

## 📜 Acceptance criteria
- [x] Design ticket is finalized and ready for merge [#1056]
- [x] Develop ticket is finalized and ready for merge [#1047]
  - https://github.com/cds-snc/gcds-examples/pull/14
- [x] #1149
  - https://github.com/cds-snc/gcds-docs/pull/430
 - [x] Content ticket is finalized and ready for publishing [#1058] 

## 📝 More info
This ticket only tracks the complete of this specific template.

## ⛔️ Blocker
- Blocked by #1149 ([Documentation: Template Overview and Basic page template #1149](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1149))

### Images

- [Basic page preview image](https://drive.google.com/file/d/1rBjxKvGDr42qO3KeI923Sw_QjPBsGN9k/view?usp=drive_link)
- [Basic page (with On this page) preview image](https://drive.google.com/file/d/15UIuhX4V_ClnMizmoWeLGGl1tP_1WYTL/view?usp=drive_link)

**Comment by SmartMouthWords** [comment]
Here's the [basic page template draft](https://docs.google.com/document/d/1D0gI2gSNZJF9FFN__aCYPSk1l_j0WAoe5xly1Oje5Fo/edit?tab=t.0). Finalizing a few pieces tomorrow but I'm not expecting the page structure to change.

**Comment by SmartMouthWords** [comment]
Basic page is ready in [FR](https://docs.google.com/document/d/1nbUtOPg9gAp_vkXO0N4zkWItp148UsAWA-akEyP1Sx8/edit?tab=t.0#heading=h.gjdgxs) and [EN](https://docs.google.com/document/d/1D0gI2gSNZJF9FFN__aCYPSk1l_j0WAoe5xly1Oje5Fo/edit?tab=t.0). 

Re-design of [template overview page](https://www.figma.com/design/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?node-id=15046-4281) to solve card issue ready in English and sent for translation.

**Comment by SmartMouthWords** [comment]
French ready now too. <img width="529" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekZ2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37d15114bfac181f46406107b6d46d61cb4e6c54/Screenshot%202024-10-24%20at%209.12.20%E2%80%AFAM.png" alt="Screenshot 2024-10-24 at 9.12.20 AM.png" />
<img width="601" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekp2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0540340b6871816c84bd4723cc8b9ab3311c54b/Screenshot%202024-10-24%20at%209.12.32%E2%80%AFAM.png" alt="Screenshot 2024-10-24 at 9.12.32 AM.png" />

**Comment by daine** [comment]
I've updated the ticket to reflect what else needs to be done to complete it

Here are the steps in more detail:

1. Publish figma file
2. Merge github PR to main
3. Update the documentation website with the published links
4. Merge documentation website PR to main to publish it

**Comment by daine** [comment]
Currently blocked by the token updates

**Comment by daine** [comment]
The code templates have been merged, and the documentation website is ready to go. Currently waiting for the links to the figma files, or if we can publish it as "coming soon"

**Comment by SmartMouthWords** [comment]
Decision to remove "coming soon section. New template here: : https://www.figma.com/design/4sdG3RjDy1VH4HregM0VxX/Documentation-site_Component-Pages?node-id=15046-4281

**Comment by daine** [comment]
Page templates have now been published
