### ISSUE TITLE
Pattern Inventory

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#120]
**TODO**
- [ ] Research and catalog current implementation of skip to content

**Outcomes**
- Have a visual reference of current implementation of skip to content to add to button model and style requirements

**Deliverables**
- Update Canada.ca reference section of model and style requirements document.

**Estimated Effort**
- [x] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Comment by ethanWallace** [comment]
Updated [Button - model and style requirements](https://docs.google.com/document/d/1nS-yXZGMkKBZfFUR9zybBeDP1Lnmrj2_N9R9MuUTw0I/edit#heading=h.4enoya45geof) with reference styles and new skip-to-content task.
