### ISSUE TITLE
Define types, tasks, variants and states

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#121]
**TODO**
- [ ] Define types, tasks, variants and states using the pattern inventory

**Outcomes**
- Have clearly defined types, tasks, variants and states based current component implementation

**Deliverables**
- Type, task, variant, and state options for the skip to content component filled out in the model and style requirements document

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Comment by ethanWallace** [comment]
Not relevant to this component
