### ISSUE TITLE
Publish Notice component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1217]
## 📇 User story
Publish the pieces needed for the Notice component

### Design 
- [x] Component in figma EN is merged
  - [Figma file](https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/branch/Uq2iUvQPdgYwcQFh0xFzhH/GC-Design-System?node-id=23721-2461&node-type=canvas&t=gTytzcn1TfUs9RrR-0)
- [x] Component in figma FR is merged

### Content
- [x] Done when content for the documentation, design and code templates has been approved
- [x] Done when the [content badge status](https://docs.google.com/document/d/1O0yY_VwkXWV2uQ3EPKovzTx6-VFdRaoHRiNuiLXvjJ0/edit?tab=t.0) has been set to "Published" 

### Development
- [x] Done when development has approved and merged the component PR in github
- [x] Done when the component packages has been released on NPM

### Documentation
- [x] Done when designs (EN and FR) has been published, with the links (github, figma) updated on the documentation website
- [x] Done when documentation has been published on the website (guidance - code, design, use case)

## 📜 Acceptance criteria
- [x] Design ticket is finalized and ready for merge [#1135]
- [x] Develop ticket is finalized and ready for merge [#269]
  - https://github.com/cds-snc/gcds-components/pull/627
- [x] Documentation and Content ticket is finalized and ready for publishing [#963] 
- [x] Documentation is finalized and ready for merge [#1287]

## ⛔️ Blockers

**Comment by ethanWallace** [comment]
Awaiting translation of Notice documentation

**Comment by SmartMouthWords** [comment]
Translation expected by November 27

**Comment by daine** [comment]
Blocked by the content and guidance ticket
- #963

**Comment by SmartMouthWords** [comment]
Bilingual review complete. Ready to publish. 
[French version](https://docs.google.com/document/d/1eAGs6Yjw3vhvXcIA4wrqgQK0YXYuvQ_FCMFQI6SIs_8/edit?tab=t.0)
[English version](https://docs.google.com/document/d/1O0yY_VwkXWV2uQ3EPKovzTx6-VFdRaoHRiNuiLXvjJ0/edit?tab=t.0)

**Comment by SmartMouthWords** [comment]
Alt text for components overview Notice thumbnail:  
"A blue vertical line truncated at the top by a blue circle, representing the guide line and icon, sits to the left of a stack of three thick grey lines. The top dark grey line represents the heading and the other two represent the lines of text."
French:
"Une ligne bleue verticale tronquée par un cercle bleu, représentant la ligne guide et l’icône, se situe à gauche de deux épaisses lignes grises pâle alignées sous une ligne grise foncée représentant un titres et des lignes de texte."

**Comment by daine** [comment]
This is done, released and published
