### ISSUE TITLE
Audit & Update components in Figma to use text styles & spacing 

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1219]
As a designer on the GC Design System team...
I want our Figma text styles to reflect the latest typography decisions...
so that our components and templates can help achieve a consistent typographic hierarchy across design assets.

## Done when
- [x] All components have been reviewed in EN Figma library
   - [x]  Breadcrumbs 
   - [x]  Button 
   - [x]  Card 
   - [x]  Checkbox 
   - [x]  Container
   - [x]  Date modified
   - [x]  Date input
   - [x]  Details
   - [x]  Error Message
   - [x]  Error Summary 
   - [x]  Fieldset 
   - [x]  File uploader
   - [x]  Grid
   - [x]  Heading
   - [x]  Icon 
   - [x]  Input
   - [x]  Language toggle
   - [x]  Labels
   - [x]  Legends
   - [x]  Link 
   - [x]  Mobile nav
   - [x]  Notice 
   - [x]  Pagination
   - [x]  Radio group
   - [x]  SR
   - [x]  Search
   - [x]  Select 
   - [x]  Side nav
   - [x]  Stepper
   - [x]  Spacing component (see styles page)
   - [x]  Text
   - [x]  Text Area
   
- [x] All components have been reviewed in FR Figma library
   - [x]  Breadcrumbs 
   - [x]  Button 
   - [x]  Card 
   - [x]  Checkbox 
   - [x]  Container
   - [x]  Date modified
   - [x]  Date input
   - [x]  Details
   - [x]  Error Message
   - [x]  Error Summary 
   - [x]  Fieldset 
   - [x]  File uploader
   - [x]  Grid
   - [x]  Heading
   - [x]  Icon 
   - [x]  Input
   - [x]  Language toggle
   - [x]  Labels
   - [x]  Legends
   - [x]  Link 
   - [x]  Mobile nav
   - [x]  Notice 
   - [x]  Pagination
   - [x]  Radio group
   - [x]  SR
   - [x]  Search
   - [x]  Select 
   - [x]  Side nav
   - [x]  Stepper
   - [x]  Spacing component (see styles page)
   - [x]  Text
   - [x]  Text Area
   
- [x] All components sitting in branches have been reviewed
- [x] All posters in EN library have been reviewed 
- [x] All posters in FR library have been reviewed

## Acceptance criteria
- [x] All text styles match the typography specifications (name, size, line height, typeface)
- [x] Has folder: **Desktop** (for EN desktop text styles)
- [x] Has folder: **Mobile** (for FR mobile text styles)

## Task flow
1. Review each components in main including EN / FR
2. If differences is being identified, document it and  apply text styles where they dont exist 
3. Consolidate doc where we have identified manual text styles where it was not applied initially 

## 🚫 Out of scope
- Header (discussed redesign to fix some issues so not doing)
- Topic Menu (very low priority so not doing given the time constraint)
- Top nav (discussed redesign to fix some issues so not doing)
- Signature (update doesn't really effect this component)
- Footer (discussed redesign to fix some issues so not doing)

**Comment by ClementineHahn** [comment]
Dev work is a dependency for this

**Comment by ClementineHahn** [comment]
@RavinaSamaroo working on continue to audit components to check more of this list
