### ISSUE TITLE
Data model

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#122]
**TODO**
- [ ] Define data model from previously completed requirements document

**Outcomes**
- Basic data model illustrating how to use component 

**Deliverables**
- Basic data model illustrating how to use component in requirements document

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Comment by ethanWallace** [comment]
Not relevant to this component
