### ISSUE TITLE
Product Inventory

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#123]
**TODO**
- [ ] Research and catalog current implementation of navigation

**Outcomes**
- Have a visual reference of current implementation of navigation to help define types, variants, and states of new component.

**Deliverables**
- Filled out Canada.ca reference section of model and style requirements document.

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic
