### ISSUE TITLE
Define types, tasks, variants and states

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#124]
[Site menu - Model and Style Requirements](https://docs.google.com/document/d/1GWGwf1nvyPuPOfROobSJBp-GmV8iRhWZRkHaAwoYwgs)

**TODO**
- [x] Define types, tasks, variants and states using the pattern inventory

**Outcomes**
- Have clearly defined types, tasks, variants and states based current component implementation

**Deliverables**
- Type, task, variant, and state options for the navigation component filled out in the model and style requirements document

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [x] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Comment by ioanacontu** [comment]
Requirements doc for navigation has some of this discussion documented.

**Comment by ethanWallace** [comment]
Basic types, tasks, variants, and states based on discussions in the [requirements doc](https://docs.google.com/document/d/1GWGwf1nvyPuPOfROobSJBp-GmV8iRhWZRkHaAwoYwgs).

**type:** N/A
**desktop-task:** topbar | sidebar
**mobile-task:** drawer | toolbar
**variant:** left | center | right | split
**interaction-state:** default | hover | focus
**data-state:** closed | open
