### ISSUE TITLE
Data Model

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#125]
**TODO**
- [ ] Define data model from previously completed requirements document

**Outcomes**
- Basic data model illustrating how to use component 

**Deliverables**
- Basic data model illustrating how to use component in requirements document

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Comment by ethanWallace** [comment]
[Data model in requirements doc](https://docs.google.com/document/d/1GWGwf1nvyPuPOfROobSJBp-GmV8iRhWZRkHaAwoYwgs#heading=h.fa6pcp30tuku)

``` html
<gcds-menu
  type=N/A
  desktop-task="topbar"   	  // vs. sidebar
  mobile-task="drawer"    	  // vs. toolbar 
  variant="left"    	 // vs. center, right, split 
  interaction-state="default"   // vs. hover, focus 
  data-state=”closed”    	 // vs. open
  lang="en"          	// vs. fr
  sticky=”false”    	//  vs. true
>
   HTML List Element
</gcds-menu>
