### ISSUE TITLE
Update spacing variables in Figma

### ISSUE THREAD

**Issue by realdylanzheng** [cds-snc/design-gc-conception#1253]
As a designer on the GC Design System team...
I want our Figma text styles to reflect the latest spacing decisions and [specifications](https://docs.google.com/document/d/1YC3O3Z5lHd79wCqJmB4OvC6zZeexOViT-hCtmVORGgM/edit?tab=t.obrud5gb1wha#heading=h.6kw3ajdqxsau)...
so that our components and templates can help achieve a consistent spacing hierarchy across design assets.

# Done when
- [x] Spacing variables have been updated or created in EN Figma library (main branch)
- [x] Spacing variables have been updated or created in FR Figma library (main branch)
- [x] Spacing variables have been reviewed by at least 1 designer
- [x] Spacing variables have been reviewed by at least 1 developer

# Acceptance criteria
### Spacing variables / tokens
- [x] Each variable must match the [spacing specifications](https://docs.google.com/document/d/1YC3O3Z5lHd79wCqJmB4OvC6zZeexOViT-hCtmVORGgM/edit?tab=t.obrud5gb1wha#heading=h.6kw3ajdqxsau)

# Task flow
1. In main, update or create each spacing variable to reflect the spacing updates

**Comment by ClementineHahn** [comment]
@SmartMouthWords to update the card description

**Comment by ClementineHahn** [comment]
Missing @melaniebmn review to consider this done

**Comment by melaniebmn** [comment]
Reviewed and looks good!
