### ISSUE TITLE
Update text styles in Figma to match typography specifications

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/design-gc-conception#1259]
As a designer on the GC Design System team...
I want our Figma text styles to reflect the latest typography decisions and [specifications](https://docs.google.com/document/d/1duGEYoerJaYj_6oGKFGJtLv6PaOS0SUcRlftNbe33iA/edit?usp=sharing)...
so that our components and templates can help achieve a consistent typographic hierarchy across design assets.

# Done when
- [x] Text styles have been updated or created in EN Figma library (main branch)
- [x] Text styles have been updated or created in FR Figma library (main branch)
- [x] Text styles have been reviewed by at least 1 designer
- [x] Text styles have been reviewed by at least 1 developer

# Acceptance criteria
### Text styles
- [x] Each text style must match the [typography specifications](https://docs.google.com/document/d/1duGEYoerJaYj_6oGKFGJtLv6PaOS0SUcRlftNbe33iA/edit?usp=sharing) in: name, size, line height, typeface

### Structure and organization
- [x] Desktop text styles are in folder: **Desktop**
- [x] Mobile text styles are in folder: **Mobile**

# Task flow
1. In main, update or create each text style to reflect the typography specifications

**Comment by SmartMouthWords** [comment]
@nmakuch to complete day of release. Tentative release date: December 5

**Comment by ClementineHahn** [comment]
Waiting dev review to close this : in the main file, variables tab

**Comment by ClementineHahn** [comment]
after dev review on spacing , needs a few updates more that are taking care of by #1219
dev @melaniebmn will review typo today and then good to close

**Comment by melaniebmn** [comment]
Global typography variables look good to go :thumbsup:
