### ISSUE TITLE
Style API

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#126]
**TODO**
- [ ] Define style API requirements for component

**Outcomes**
- List of CSS properties users can access through component properties.

**Deliverables**
- Filled out style properties section of model and style requirements section

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
