### ISSUE TITLE
Develop stencil component

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#127]
**TODO**
- [ ] Develop basic functionality of component based on model and style requirements documentation

**Outcomes**
- Basic JS component

**Deliverables**
- Functional JS component with limited styling

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by ethanWallace** [comment]
First version is up on [site-menu branch](https://github.com/cds-snc/gcds-components/tree/site-menu).

Things that still need to be done:
- Fix split variant
- Add toolbar mobile-task
- Optimize CSS loading
- Add data states
- Add i18n

**Comment by ethanWallace** [comment]
Scoped to our use case on the alpha documentation site. Will revisit after MVP.
