### ISSUE TITLE
Update gcds-button component with new task

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#128]
**TODO**
- [ ] Code new skip-to-content task into button components

**Outcomes**
- Expand button component's functionality to contain skip to content task

**Deliverables**
- New task in gcds-button component

**Estimated Effort**
- [x] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Comment by ethanWallace** [comment]
Added skip-to-content to gcds-button component. https://github.com/cds-snc/gc-ds-button/pull/3
