### ISSUE TITLE
Define button styles

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#145]
**TODO**
- [ ] Define button colours
- [ ] Define typography 
- [ ] Define margins
- [ ] Define padding
- [ ] Define width/max-width
- [ ] Define icon position

**Outcomes**
- Make design decisions that can support the button component. 

**Deliverables**
- button styles are defined in Figma.
- rationale for each design use is provided (primary, secondary, destructive, disabled, button link).

**Acceptance criteria**
- visual elements observe colour and contrast requirements (WCAG 2.1 AA).
- feature meets WCAG 2.1 AA target size requirements.
- feature provides equal service in French and English.

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
- colours that are not meant for the button component. 
- icon library.
