### ISSUE TITLE
Design skip-to-content

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#147]
**TODO**
- [ ] Define text size
- [ ] Define padding
- [ ] Define focus states
- [ ] Define interaction

**Outcomes**
Skip-to-content button design is defined and ready to implement.

**Deliverables**
- button styles are defined in Figma.
- rationale for each design use is provided (when and how to use).

**Acceptance criteria**
- visual elements observe colour and contrast requirements (WCAG 2.1 AA).
- feature meets WCAG 2.1 AA target size requirements.
- feature provides equal service in French and English.

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by ioanacontu** [comment]
Dependency with the more general button styling and tokens.

**Comment by nmakuch** [comment]
Skip to content button demo

https://sandbox-brown.vercel.app/skip

**Comment by nmakuch** [comment]
If we go the route of a button for this UI element (the other option is an anchor link) we shouldn't be designing a brand new style but using the appropriate style of button for the priority of the task (primary, secondary, tertiary)

Here I've made a gut decision and set it up as a secondary button but I'm not a keyboard user and can't really make that call without doing some more research.

Should also note that since the user can't see the button in it's default state, the first thing they will see is the button's focus state, it's possible that the user might see it on the way out if we use an animation like I've done in that demo link. I think I might be over thinking this a bit :s

I've also put it at the top left hand corner of the page as to not disrupt the flow that already exists on the page.
