### ISSUE TITLE
Add requirements for skip-to-content in the Buttons requirements document

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#148]
**TODO**
- [ ] Add requirements for skip-to-content in the Buttons requirements document

**Outcomes**
- Requirements for skip-to-content  in the Buttons requirements document reflect design and implementation decisions. 
- All requirements and decisions are documented in a single source of truth.

**Deliverables**
- Skip-to-content is documented in the TO ADD section of [this document](https://docs.google.com/document/d/1nS-yXZGMkKBZfFUR9zybBeDP1Lnmrj2_N9R9MuUTw0I/edit#heading=h.m8vt9bn9zlq). 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by ioanacontu** [comment]
Is there, but is everywhere it needs to be? When will this be done?

**Comment by ioanacontu** [comment]
Nick is working on the design for skip-to-content. As he's doing research, he'll add infos in the requirements doc as well.
