### ISSUE TITLE
Skip-to-content content

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#151]
**TODO**
- [ ] 

**Outcomes**
- 

**Deliverables**
- 

**Estimated Effort**
- [x] XS: 1 to 2 hours
- [x] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by ioanacontu** [comment]
Function for skip-to-content to be detailed/defined. To add to the Button requirements document.

**Comment by SmartMouthWords** [comment]
- [ ] research skip-to-content
- [ ] write content for main button page
- [ ] write content for design page

**Comment by SmartMouthWords** [comment]
https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/Drafting-data?node-id=1478%3A19

**Comment by SmartMouthWords** [comment]
Can be found in button component page in [Figma Documentation site desktop](https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/Documentation-site%2FMVP%2FIA?node-id=2823%3A1494)
