### ISSUE TITLE
Research and catalog current implementation of text input

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#152]
[Basic text inputs - Model and Style requirements](https://docs.google.com/document/d/1Nq6EXxH3L5LbvT8bkku50n62Xde1xDD0e30fq5POueM)

**TODO**
- [x] Research and catalog current implementation of navigation

**Outcomes**
- Have a visual reference of current implementation of text inputs to help define types, variants, and states of new component.

**Deliverables**
- Filled out reference section of model and style requirements document.

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
