### ISSUE TITLE
Wireframe page layout, headings and visuals

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#154]
**TODO**
- [ ] try out storybook for it

**Outcomes**
- 

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by samsadasivan** [comment]
Work is mostly done, documentation and decisions will be updated here by end of the week :)

**Comment by samsadasivan** [comment]
Desktop wireframes and the associated flows for MVP are documented under *[1] Documentation site: desktop* ![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/d53af3bb-9170-49f8-a6b9-5e5c96b23f87)

https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/GC-DS-Product-Design?node-id=2823%3A1030

**Comment by samsadasivan** [comment]
**Navigation #design-decision**

Design challenge #1 - Component pages can become very long and inconsistent depending on the type of component. Made the contextual menu appear per component, rather than per category (basic/forms). Users will want to look for specific guidance/rationale without skimming through all the content. 

Design challenge #2 - Users will want to see all the components available

- First click will drop down three main items: Overview, Basic, Forms 
- The “On this page” skip links will act as the contextual menu per component to link to the main headers of the page, this element will be sticky on desktop
- On mobile the “On this page” links will act as skip links and there will be a “back to top” link at the bottom
added a page around component overview to see what is available in the packages “basic” and “forms” 
- Forms_landingpage will be “Forms guidance” and clicking on the “Forms” item in the dropdown will just reveal the list of components
Risk: navigation will long enough to go below the fold as we start to add more components, will have to consider a left side main menu after MVP 

![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/7593e5b9-576c-4e8e-986d-aaf38c974132)

**Comment by SmartMouthWords** [comment]
Component pages follow consistent content structure: 
1. definition
2. when to use (general and by subtype)
3. how to modify, depart from the default
4. use cases
5. related components
6. guidance on accessibility and design

**Comment by SmartMouthWords** [comment]
Can be found in [Figma Documentation site desktop](https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/Documentation-site%2FMVP%2FIA?node-id=2823%3A1494)
