### ISSUE TITLE
Define button states

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#158]
**TODO**
- [ ] default
- [ ] hover
- [ ] focus
- [ ] active
- [ ] active and focus
- [ ] disabled

**Acceptance Criteria**
- button styles are defined in Figma: default, hover, focus, active, active and focus, disabled.
- visual elements observe colour and contrast requirements (WCAG 2.1 AA).

**Outcomes**
- 

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by nmakuch** [comment]
This is what I'm proposing for states

![Screen Shot 2022-02-28 at 19.54.15.png](https://images.zenhubusercontent.com/6114083c9f04be0cc22aa403/17dfbda8-dc73-4c44-aa60-a6e1963a5ab3)

[And you can view them live here](https://sandbox-brown.vercel.app/buttons)

**Comment by nmakuch** [comment]
Note that the rounded border is not possible due to CSS limitations

**Comment by nmakuch** [comment]
I think we need to discuss which buttons can have which variants because I don't think every button will need access to all of them. For example a skip-to-content link button is solid and would never need an outlined version. If we need designs for these other ones I can do them in the future

**Comment by nmakuch** [comment]
I've tested all  bg and text colour combos to ensure it meets WCAG AA at minimum

**Comment by nmakuch** [comment]
Some rationale

https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/Drafting-data?node-id=2182%3A177
