### ISSUE TITLE
Develop input stencil component

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#159]
**TODO**
- [x] Develop basic functionality of component based on model and style requirements documentation

**Deliverables**
- Functional JS component with limited styling

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
