### ISSUE TITLE
Input field content

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#167]
**TODO**
- [ ] 

**Outcomes**
- 

**Deliverables**
- general and design content pages for input fields, including text area and field label

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by SmartMouthWords** [comment]
- [x] research error message guidance
- [x] write content for page
- [ ] review for consistent layout and content  
- [ ] copy edit
