### ISSUE TITLE
Forms page content

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#168]
**TODO**
- [ ] 

**Outcomes**
- 

**Deliverables**
- Content for the forms pattern page

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by SmartMouthWords** [comment]
- [x] research forms guidance
- [x] write content for forms guidance page
- [ ] review for consistent layout and content  
- [ ] copy edit
