### ISSUE TITLE
Error message component content

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#169]
**TODO**
- [ ] 

**Outcomes**
- Content for error message general and design pages.   

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by SmartMouthWords** [comment]
- [x] research error message guidance
- [x] write content for page
- [ ] review for consistent layout and content  
- [ ] copy edit
