### ISSUE TITLE
Structure documentation site

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#171]
**TODO**
- [x] Structure documentation site based on [figma file](https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/GC-DS-Product-Design?node-id=2823%3A1030)

**Deliverables**
- Basic site structure setup. No content on the pages yet

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by ethanWallace** [comment]
Published English side of site to match new IA https://cds-snc.github.io/alpha-design-system-documentation/en/
