### ISSUE TITLE
Publish content: foundations

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#173]
**TODO**
- [x] Foundations

**Deliverables**
- Bilingual content published for foundations section documentation site

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by SmartMouthWords** [comment]
- [ ] review for consistent layout and content  
- [ ] structure and write content
- [ ] copy edit
