### ISSUE TITLE
Publish content: extra pages

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#175]
**TODO**
- [x] Terms and conditions
- [x] Privacy policy
- [x] home/landing

**Deliverables**
- Published content on extra pages

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by abdul-CDS** [comment]
Are we using CDS or DTO existing terms and policies?
