### ISSUE TITLE
Styling documentation site

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#178]
Will place an E (Ethan) or M (Melanie) beside the todo item to show who is working on it.

**TODO**
- Landmarks
   - [x] In Development Banner      (M)
   - [x] Header      (M)
   - [x] Footer       (M)
   - [x] Main. (E)
   - [x] Aside / main (sidebar layout)   (E)
- Menus
   - [x] Breadcrumbs        (E)
   - [x] Context menu (on this page)       (E)
- Documentation page
   - [x] View code (gathering more on this) (E)
   - [x] Stage chip/pill (E)
   - [x] Showcase columns
- Page
   - [x] Remove Landing/language select page ([This page](https://cds-snc.github.io/alpha-design-system-documentation/)) (M)
   - [x] Overview lists
- Misc
   - [x] Container class      (M)
   - [x] "Design system" element(link?) in main nav (E)
   - [x] Hide heading anchors (E)
   - [ ] Lead paragraph in documentation
   - [x] Favicon

**Deliverables**
- Styled alpha documentation site
