### ISSUE TITLE
Packaging our components

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#179]
**TODO**
- [x] Improve readme for npm package English and French
- [x] Readme for npm [FR]
- [x] Move npm package over to CDS org

**Deliverables**
- NPM package published under cds org on npm with bilingual  readme,

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic
