### ISSUE TITLE
Add design.alpha.canada.ca domain to doc site

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#180]
**TODO**
- [x] Submit pull request to https://github.com/cds-snc/dns
- [ ] Configure Netlify to use custom domain

**Deliverables**
- Documentation site hosted on design.alpha.canada.ca

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic
