### ISSUE TITLE
Adjusting the phase banner

### ISSUE THREAD

**Issue by nmakuch** [cds-snc/design-gc-conception#183]
We need to restyle the phase banner a little bit. The current banner is center aligned and we shouldn't be mixing text alignment like that. We also want to align text wherever possible. 

**TODO**
- [x] Align the banner with the content container on the site
- [x] Ensure it scales down a bit

**Outcomes**
- The banner will align with the left edge of the content container
- Alpha badge will align with the flag in the goc signature
- Banner text will align with the text in the goc signature

**Deliverables**
- Pull request on the alpha doc site

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ x ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
- Don't have a lot of time to spend on media queries, but we can get to that later
