### ISSUE TITLE
Integrate tokens into documentation page

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#185]
**TODO**
- [ ] Integrate tokens into documentation page

**Outcomes**
- 

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
