### ISSUE TITLE
Optimize gcds-components package

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#186]
**TODO**
- [x] Minify CSS
- [ ] Minify extra JS files

**Outcomes**
- Optimize gcds-components package to be a more compact package for better loading times.

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
