### ISSUE TITLE
Documentation site: Keep formatting of copied code

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#187]
**TODO**
- [x] Keep formatting of copied code 
- [ ] Test
- [ ] Review

**Outcomes**
- Copied code keeps formatting when pasted

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
