### ISSUE TITLE
Documentation site - Only one submenu open at a time - topbar

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#188]
**TODO**
- [ ] Fix, only one submenu item open at a time
- [ ] Test
- [ ] Review

**Outcomes**
- Only one submenu item open at a time

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
