### ISSUE TITLE
Input - Using size attribute makes input non-responsive

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#189]
**TODO**
- [ ] Using size attribute makes input non-responsive
- [ ] Test
- [ ] Review

**Outcomes**
- 

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
