### ISSUE TITLE
PoC - DECD Design System exploration

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#190]
**TODO**
- [x] Select components for POC
- [ ] Review design, code and guidance available in DECD DS library
- [ ] Document findings

**Outcomes**
- pick 1 or 2 components from the DECD library and determine how much of it we can use. Desired outcome is to document any modifications/peculiarities/edge cases/pitfalls to consider if we were to scale this approach.

**Deliverables**
- Documentation that guides next stpes

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
- Actual implementation of components or designs beyond what is necessary for PoC

**Comment by ethanWallace** [comment]
Using three components for exploration
- A component we have built (Button)
- A component we are looking to build (Header)
- A component we haven’t started looking at at all (Message)
