### ISSUE TITLE
Template for component page content

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#192]
**TODO**
- [x] Document component page elements and instructions
- [x] Explore format
- [x] produce prototype 

**Outcomes**
- Make it easier for team members to contribute design system documentation 

**Deliverables**
- Prototype of component page template

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ X ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by SmartMouthWords** [comment]
Prototype: https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/Documentation-site%2FMVP%2FIA?node-id=2823%3A1030
