### ISSUE TITLE
Document content design workflow and needs 

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#193]
**TODO**
- [x] document workflow
- [x] identify content design priorities for design system work
- [x] propose some possible solutions

**Outcomes**
- [ ] Alignment on a plan to ensure equal delivery of French and English 

**Deliverables**
- workflow and short proposal

**Estimated Effort**
- [ X ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by SmartMouthWords** [comment]
Content design needs and workflow [https://docs.google.com/document/d/1aPujbu3-hNTKETX2VvvQDJ4hDgOOQ-deSzvzuckl-Vs/edit#heading=h.y63qfozi294d](url)

**Comment by SmartMouthWords** [comment]
[Workflowdiagram](https://miro.com/app/board/uXjVOnu4cXA=/)
