### ISSUE TITLE
Header component requirements document

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#194]
**TODO**
- [ ] Basic categorization of components vs patterns/templates
- [x] Catalog component dependencies (components that make up the header component)
- [x] Basic data model

**Outcomes**
- All requirements and decisions are documented in single source of truth

**Deliverables**
- [Header - Model and Implementation Requirements](https://docs.google.com/document/d/14KSnA0d7WKU-xZV_6bC9YzMJbCs5DBGMcr4oCSI8Q3U/edit?usp=sharing)

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [x] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
- Header design
