### ISSUE TITLE
Add top-nav and side-nav styling

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#197]
**TODO**
- [x] Add top-nav and side-nav styling

**Outcomes**
- 

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by ClementineHahn** [comment]
Update description to add acceptance criteria @ClementineHahn
