### ISSUE TITLE
Add guidance content for the docs grid component page

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#198]
**TODO**
- [x] Add guidance content for the grid component page using content template

**Outcomes**
- Draft documentation for grid component

**Deliverables**
- Draft documentation for grid component

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
