### ISSUE TITLE
Header: Create prototype

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#201]
**TODO**
- [x] Prototype gcds-lang-toggle
- [x] Prototype gcds-signature
- [x] Prototype gcds-header (combine them all together)

Deliverables
- Basic Header component with basic styles
