### ISSUE TITLE
Figma Integration: Connect component documentation to Figma page

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#206]
**TODO**

- [x] Create master design Figma file
- [x] Add component files to master using the token values
- [x] Link to file from Doc. site page
- [ ] Research: public Figma pages

**Outcomes**
First integrated link between component documentation and Figma

**Deliverables**
At least one component that links directly from documentation site to Figma where component design is available
Buttons, Text input, Text area

- [ ] XS: 1 to 2 hours
- [ ]  S: half a day
- [ ]  M: 1-2 day
- [ ]  L: 1 week
- [ ]  XL: Move to an epic

**Out of scope**
Multiple components linked to Figma
