### ISSUE TITLE
HEADER - GC signature link: update the destination so that it points to the home page in each official language, rather than the canada.ca language choice page

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#208]
**TODO**
- [ ] Update EN link
- [ ] Update FR link

**Outcomes**
- Clicking on the GC Signatures in both languages directs to the home page in each official language rather than the canada.ca language choice page

**Deliverables**
- Updated EN and FR links

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by ethanWallace** [comment]
Will be handled by gcds-header
