### ISSUE TITLE
HEADER - Language toggle: in mobile view, update label so that it uses FR or EN, for visual consistency

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#210]
**TODO**
- [ ] Language toggle: in mobile view, update label so that it uses FR or EN, for visual consistency

**Outcomes**
- 

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by ethanWallace** [comment]
Will be handled by gcds-header
