### ISSUE TITLE
HEADER - Keyline: incorporate blue keyline into the header, for visual consistency with the brand

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#211]
**TODO**
- [ ] Keyline: incorporate blue keyline into the header, for visual consistency with the brand

**Outcomes**
- Header is visually more consistent with canada.ca brand

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by ethanWallace** [comment]
Will be handled by gcds-header
