### ISSUE TITLE
HEADER: Breadcrumb trail changes

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#212]
**TODO**
- [x] Update so that it starts at Canada.ca home, to indicate integration
- [x] Update typography and styling of breadcrumb trail so that it matches the brand

**Outcomes**
- Breadcrumb trail is more consistent with Canada.ca

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
