### ISSUE TITLE
FOOTER - changes

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#213]
**TODO**
- [ ] Add date modified component
- [ ] Main footer: add main footer links, using the Canada.ca design and style 
- [ ] Sub-footer: add missing links and,  adjust size and layout to match the brand, and indicate integration
- [ ] Canada wordmark: increase size in desktop view to match the brand

**Outcomes**
- Consistent footer with brand

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by ethanWallace** [comment]
> Main footer: add main footer links, using the Canada.ca design and style
 Sub-footer: add missing links and, adjust size and layout to match the brand, and indicate integration
 Canada wordmark: increase size in desktop view to match the brand

Will be implemented by gcds-footer

> Add date modified component 

Can be done using https://www.11ty.dev/docs/dates/. Would add to the bottom of the `<main>` tag like canada.ca
