### ISSUE TITLE
TYPOGRAPHY - H1s are missing the red rule underneath that is specified at design.canada.ca

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#215]
**TODO**
- [ ] TYPOGRAPHY - H1s are missing the red rule underneath that is specified at design.canada.ca

**Outcomes**
- Header is more consistent with the brand

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by nmakuch** [comment]
Changes are in the dto-archive branch
https://github.com/cds-snc/gcds-docs/blob/dto-archive/src/styles/style.css
