### ISSUE TITLE
Separate from design.alpha.canada.ca

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#216]
**TODO**
- [x] Create branch for archiving current site for design.alpha site ([dto-archive](https://github.com/cds-snc/gcds-docs/tree/dto-archive))
- [x] Update specific designs on doc site (canada.ca stying)
- [x] Configure new build & deploy settings on Netlify
- [x] Create new Netlify site for CDS design system
- [x] Change email recipient (Contact Us)
- [x] Update URL of doc site (https://cds-snc-design.netlify.app/)

**Outcomes**
- Separate site ready for CDS Design System work using same repo

**Deliverables**
- Two separate Netlify sites using one GitHub repo, gcds-docs. 
   - `dto-archive` branch for design.alpha.canada.ca
   - `main` branch for CDS design system(no url yet)

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
