### ISSUE TITLE
Create Footer requirements document

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#217]
**TODO**
- [x] Catalog component dependencies (components that make up the footer component)
- [x] Basic data model

**Outcomes**
- All requirements and decisions are documented in single source of truth

**Deliverables**
- [Footer - Model and Implementation Requirements](https://docs.google.com/document/d/1XR5CZhXIWUkCDyLHfpUpO7bTgc84GGdigkDH-igZXhs/edit?usp=sharing)

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [x] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic
