### ISSUE TITLE
Footer: Create prototype

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#218]
**TODO**
- [ ] Prototype component based on requirements document

**Outcomes**
- An early version of the gcds-footer component

**Deliverables**
- A footer component styled like canada.ca

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
