### ISSUE TITLE
Analyze user research for npm installation process on documentation site

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#219]
**TODO**
- [x] Review research with developers
- [x] Consolidate research on installation, getting started 
- [x] Group into common themes 

**Outcomes**
- Understand what needs to be improved in the installation process  

**Deliverables**
- Analysis

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by SmartMouthWords** [comment]
Next steps
Get more insight into core use and how the documentation site design can support onboarding 
Areas to redesign content based on research: 
Homepage (more on what, quick link, links, and clarify some content)
Installation name
Add introductory text (for developers, not WET, tips, etc.)
Small adjustments to instructions (Try out)
Add CDN 
🎉 Installed
What/where next after installation
