### ISSUE TITLE
Apply Canada.ca Colour scheme 

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#220]
**TODO**
- [x] Body text: use the dark grey (#333) from the Canada.ca design, for brand consistency
- [x] Link text: for default links, use #2b4380 for brand consistency
- [x] Main accent colour: Utilize the dark blue accent more to emphasize that this is the main accent colour in the brand
- [x] Adjust the blue used in the site menu so that it does not clash with the main accent colour (the menu could use the main accent colour itself)

**Outcomes**
- Colour scheme is more consistent with Canada.ca

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by ClementineHahn** [comment]
Done in Figma but need to update the card to merge with principal
