### ISSUE TITLE
TYPOGRAPHY - Line height and content width

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#221]
**TODO**
- [ ] Adjust the line height for body copy to 165% to match the Canada.ca design
- [ ] Limit content width to 65 characters

**Outcomes**
- Typography more consistent with Canada.ca

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by nmakuch** [comment]
Changes are in the dto-archive branch
https://github.com/cds-snc/gcds-docs/blob/dto-archive/src/styles/style.css
