### ISSUE TITLE
Inventory documentation site guidance guidance on required fields

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#222]
**TODO**
- [x] check site for all guidance on required fields and markers
- [x] make necessary corrections in GitHub

**Outcomes**
- ensure consistent advice and application of required fields and markers

**Deliverables**
- add all references to required fields to [Guidance mapping](https://airtable.com/app7xvzGREZVDGuZV/tbliWh4WYrwcMFSW8/viw5mkoSbfNzjGaGU?blocks=hide)
- fix any inconsistencies

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
