### ISSUE TITLE
Design radio and checkbox components

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#224]
**TODO**
- [x] Review IRCC Figma for component designs 
- [x] Adapt UI components to fit our look and feel
- [x] Map out interactive states in figma

**Outcomes**
- Document findings (what's working, what needs to be modified)
- Create components in figma

**Deliverables**
- Figma page(s) with component designs + any modifications

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Findings**
- I skipped the active state on mobile because we haven't done this with other components
- Learned some good figma knowledge by observing how IRCC was building their radio inputs + labels
- The IRCC inputs were a little small so I used a rule of thumb from a previous project and upped ours to be 40px x 40px
- Focus styles kind of clashed a bit with our current focus styles on inputs but I've updated these in the figma document (I'm going to go into the gcds-components repo and change them next week for < input > and < textarea >)
- The reds we currently have were pretty low contrast so I had to use a red not in our current pallette (we should add it to our tokens)

**Comment by abdul-CDS** [comment]
https://www.figma.com/file/16zKKXc4pzBdRAXmbz6Ht4/Components?node-id=89%3A683

**Comment by nmakuch** [comment]
Adapted IRCC designs to create our own atoms which can be found here:
[GC Components Atoms](https://www.figma.com/file/4KWj8wnnXoq6cA6yl0dnsR/GC-Components?node-id=479%3A310)

**Comment by nmakuch** [comment]
Radio Button Page w interactive states
[GC Components Radio Buttons](https://www.figma.com/file/4KWj8wnnXoq6cA6yl0dnsR/GC-Components?node-id=462%3A110)

Checkbox Page w interactive states
[GC Components Checkboxes](https://www.figma.com/file/4KWj8wnnXoq6cA6yl0dnsR/GC-Components?node-id=462%3A320)

**Comment by nmakuch** [comment]
I went a step further and created interactive html/css versions of these states working in real time for demo and to help the dev team if they're creating these styles

Radio HTML / CSS
[Radio Buttons sandbox version](https://sandbox-brown.vercel.app/radio-buttons)

Checkboxes HTML / CSS
[Checkboxes sandbox version](https://sandbox-brown.vercel.app/checkboxes)
