### ISSUE TITLE
User onboarding journey map

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#225]
**TODO**
- [ ] Review past research with users and stakeholders for key insights related to onboarding and core use patterns
- [ ] Analyze findings 
- [ ] Map core use
- [ ] Map user onboarding journeys

**Outcomes**
- Gain a better understanding of user goals in the product for content redesign 

**Deliverables**
- Core use and onboarding journey maps
- Synthesis of relevant research findings from past year 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
- Synthesis of all research from latest research sessions
