### ISSUE TITLE
Explore making contributions work at a small scale

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#226]
**TODO**
- [ ] Document a hypothesis for the approach
- [ ] Identify constraints and criteria (team)
- [ ] Talk to potential contributors at CDS to understand their needs
- [ ] document requirements for a content management system that could test hypothesis with users

**Outcomes**
- Understand what we need to do to facilitate contributions and what we need from contributors to make a small scale contribution model work

**Deliverables**
- Requirements document for contribution needs

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
