### ISSUE TITLE
Create checkbox component requirements doc

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#228]
**TODO**
- [ ]  Basic data model
- [ ]  Pattern inventory from various design system work

**Outcomes**
- Documented requirements 

**Deliverables**
- Doc

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [x] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
