### ISSUE TITLE
Create Radio button component requirements documentation

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#230]
**TODO**
- [ ] Radio button component requirements doc
- [ ] Basic data model

**Outcomes**
- Requirements

**Deliverables**
- Requirements doc

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
