### ISSUE TITLE
Create banner component requirements documentation

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#232]
**TODO**
- [x]  Banner component requirements doc
- [x]  Basic data model
- [x]  Define verify banner

**Outcomes**
- 

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
