### ISSUE TITLE
Create a11y toolbar component requirements documentation

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#233]
**TODO**
- [ ]  A11y toolbar component requirements doc
- [ ]  Basic data model

**Outcomes**
- 

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
