### ISSUE TITLE
Create banner component requirements documentation

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#234]
**TODO**
- [ ]  Banner component requirements doc
- [ ]  Basic data model
- [ ]  Define verify banner

**Outcomes**
- 

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
