### ISSUE TITLE
Accessibility widget: Requirements

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#235]
**TODO**
- [ ] Create a11y toolbar component requirements doc
- [ ] Basic data model

**Outcomes**
- 

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by adorayi** [comment]
Checkin with Forms & Notify on this, is there a design, is there a need?
