### ISSUE TITLE
Create english + french copy for verify banner

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#238]
**TODO**
- [ ] Create / review current english copy
- [ ] Create french copy

Current copy:

An official website of the Government of Canada
Find out how to recognize them

**Official websites use canada.ca or gc.ca**
Federal government websites most often either use canada.ca or gc.ca. Before sharing sensitive information, make sure you're on a federal government site.

**Secure Government of Canada websites use HTTPS**
The https:// ensures that you are connecting to the official website and that any information you provide is encrypted and transmitted securely.

**Outcomes**
- 

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by melaniebmn** [comment]
![Screen Shot 2022-07-07 at 10.34.56 AM.png](https://images.zenhubusercontent.com/620163ddfc3b6d028ba2c1a7/bfc68255-f55f-472b-8b76-859ddc7f24df)

**Comment by SmartMouthWords** [comment]
Research: 
Examples of text from other government departments: 
Immigration
[](https://www.cic.gc.ca/english/helpcentre/answer.asp?qnum=1206&top=31)
* it looks like an official Government of Canada site but it is only in one language and does not have the Canada.ca URL or a URL that ends with “.gc.ca.”
* you must provide personal information, financial information or make a deposit before you even start the application process.
* there is no padlock in the browser window or https:// at the beginning of the web address to show it is a secure site. Even if the site appears secure, be cautious.

Competition Bureau
[](https://www.canada.ca/en/competition-bureau/news/2019/08/government-websites-spot-the-legitimate-among-the-fakes.html)

* Make sure your browser is up-to-date: Browser filters can help detect fake websites.
* Look for contact information: Genuine Government of Canada websites will always list a point of contact. Generally, look for Canada.ca or gc.ca e-mails with no typos. Official government websites will also never use private email services such as Hotmail, Yahoo mail or Gmail. Look for both of Canada’s official languages: Information on federal government websites is always available in English and French.
If you’re unsure:
* Don’t give out personal details: Be cautious with websites that demand that you transfer money or provide information such as bank account numbers or personal identification, like your Social Insurance Number.
* Contact 1 800 O-Canada (1-800-622-6232) to obtain general information on programs and services.



Canada.ca blog
[](https://blog.canada.ca/2020/08/10/canadadotca-trusted-source)
Recognition of gc.ca higher than Canada.ca

Example of a site not using gc.ca or Canada.ca
[](https://www.antifraudcentre-centreantifraude.ca/index-eng.htm)
