### ISSUE TITLE
Quick clean up existing documentation site

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#242]
**TODO**
- [x] Connect content by linking to other pages and sections (especially from landing page)
- [x] adjust some styling (i.e., numbered lists and spacing) 
- [ ] other quick fixes  

**Outcomes**
- Make site a little easier to use and look at

**Deliverables**
- increase links throughout site
- cleaner site for sharing / testing  

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by SmartMouthWords** [comment]
Awesome @melaniebmn !
Agree, the homepage is where there's the most opportunity. I was also thinking we might link any pages we have components built for that are listed in the Related components sections of each page.
