### ISSUE TITLE
Government Design Systems 

### ISSUE THREAD

**Issue by sarahhobson** [cds-snc/design-gc-conception#243]
**TODO**
- [x] Identify scope
- [x] Identify research questions 
- [x] Conduct research 
- [x] Synthesize findings 
- [x] Share findings with team 
- [x] Share with Platform management

**Outcomes**
- Understanding how other governments have managed and implemented their design systems 

**Deliverables**
- A 1-pager comparing different government design system models 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
- Examining other government design systems from a design or development perspective

**Comment by sarahhobson** [comment]
[Comparative Analysis](https://docs.google.com/document/d/1jU5aOdgupGV8dZpKwMxjlzI6S_Jcm3zwwgt5SFRiYeM/edit#)

**Comment by sarahhobson** [comment]
[Working Document](https://docs.google.com/document/d/1jU5aOdgupGV8dZpKwMxjlzI6S_Jcm3zwwgt5SFRiYeM/edit#)
