### ISSUE TITLE
Add instructions and set up help for the component page template in Figma

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#244]
**TODO**
- [x] archive the prototype file
- [x] add autoformatting to the file
- [x] add instructions for use
- [ ] add examples

**Outcomes**
- Have more team members be able to use the file

**Deliverables**
- a cleaned up Figma template to continue testing with the team and iterating on

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [x] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by SmartMouthWords** [comment]
Updated template: [](https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/Documentation-site%2FMVP%2FIA?node-id=5156%3A2977)
Will add examples at a later time
