### ISSUE TITLE
Reformat site menu component

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#246]
**TODO**
- [ ] Reformat site menu component based on new design
- [ ] Add extra functionality to sidebar layout
- [ ] Add responsive layout for main to sidebar layout

**Deliverables**
- Fully functional and accessible site menu component

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic
