### ISSUE TITLE
Design: Selector component

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#247]
**TODO**
- [ ] Design for dropdown component

**Outcomes**
- Figma design page
- Considerations for accessibility
- Review IRCC Figma for similar component
- Review ESDC Figma for similar component
- Single select option
- Multiple select option

**Deliverables**
- Figma design page for dropdown component

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
