### ISSUE TITLE
Selector component

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#248]
**TODO**
- [ ] Design
- [ ] Research
- [ ] Requirements and Development
- [ ] Guidance in EN
- [ ] Guidance in FR

**Outcomes**
- Usable component with guidance and examples

**Deliverables**
- Github code
- Figma designs
- EN guidance
- FR guidance
