### ISSUE TITLE
Selector component requirements document

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#250]
**TODO**
- [ ] Create requirements doc for component

**Outcomes**
- Full review of component and considerations around model & development 
- Reviewed similar components in other GC Design Systems 

**Deliverables**
- Requirements doc

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
