### ISSUE TITLE
Selector component development

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#251]
**TODO**
- [x] Development of component, according to design and accessibility guidelines

**Outcomes**
Development of component, according to design and accessibility guidelines

**Deliverables**
- Coded component in Github, reviewed by team

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
