### ISSUE TITLE
Research: Notification & Alert usage and guidance

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#252]
**TODO**
- [ ] Research into use cases of Notifications, Alerts as components
- [ ] Guidance and usage of Notifications and Alerts as components

**Outcomes**
- Recommendations and guidance on implementing Notifications as a component

**Deliverables**
- Documented guidance and recommendations

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
