### ISSUE TITLE
Notice component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#253]
**TODO**
- [ ] Design
- [ ] Research
- [ ] Requirements and Development
- [ ] Guidance in EN
- [ ] Guidance in FR

**Outcomes**
- Usable component with guidance and examples

**Deliverables**
- Github code
- Figma designs
- EN guidance
- FR guidance

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
