### ISSUE TITLE
EN Content / Documentation: Footer component

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#258]
**TODO**
- [ ] First version of EN documentation for Footer component using documentation template
- [ ] Review of documentation
- [ ] Publishing documentation on site

**Outcomes**
- First version of documentation for component for feedback

**Deliverables**
- Published documentation page(s)

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
