### ISSUE TITLE
Research: Validators

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#262]
**TODO**
- [x] Technical research on implementing validators across different input components
- [x] Document findings

**Outcomes**
- Clear direction on how we will implement this in the product

**Deliverables**
- Documented recommendations on how to approach delivering this feature

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
