### ISSUE TITLE
Create requirements doc for select component

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#266]
**TODO**
- [ ] Create requirements doc for select component

**Outcomes**
- 

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
