### ISSUE TITLE
EN Content / Documentation: Select component

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#267]
**TODO**
- [x] First version of EN documentation for Gov Verify component using documentation template
- [ ] Review of documentation
- [ ] Publishing documentation on site

**Outcomes**
- 

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by melaniebmn** [comment]
@SmartMouthWords here is the link to the Figma page:

https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?node-id=5914%3A411
