### ISSUE TITLE
Design: Notification & Alert component

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#268]
**TODO**
- [ ] Design for notification component

**Outcomes**
- Figma design page
- Considerations for accessibility
- Review IRCC Figma for similar component
- Review ESDC Figma for similar component

**Deliverables**
- Figma design page for notification component

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
