### ISSUE TITLE
Design: Accessibility component

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#273]
**TODO**
- [ ] Design for component

**Outcomes**
- Figma design page
- Considerations for accessibility

**Deliverables**
- Figma design page for component

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
