### ISSUE TITLE
Design: Autofill component

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#276]
**TODO**
- [ ] Design for component

**Outcomes**
- Figma design page
- Considerations for accessibility
- Review IRCC Figma for similar component
- Review ESDC Figma for similar component

**Deliverables**
- Figma design page for component

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by nmakuch** [comment]
This was done a while ago 
https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/GC-Components-Main?node-id=1179%3A2761
