### ISSUE TITLE
Design: File Uploader component

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#279]
**TODO**
- [x] Design for component

**Outcomes**
- Figma design page

**Deliverables**
- Figma design page for component

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [x] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by nmakuch** [comment]
https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/GC-Components-Master?node-id=963%3A2452
