### ISSUE TITLE
Design: Error Summary

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#284]
**TODO**
- [ ] Research guidance for error summary
- [x] Design for error summaries

**Outcomes**
- Figma design page

**Deliverables**
- Figma design page for error summaries

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by melaniebmn** [comment]
The form builder team is looking for guidance around error summaries. They need to create useful error messages to tell the user how they can fix their mistake, rather than the majority pattern of “Please complete the required field to continue.”

Here is the card that outlines their current issues:
https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/cds-snc/platform-forms-client/449
