### ISSUE TITLE
Design: Accordion component

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#286]
**TODO**
- [x] Design for component

**Outcomes**
- Figma design page
- Considerations for accessibility
- Review IRCC Figma for similar component
- Review ESDC Figma for similar component

**Deliverables**
- Figma design page for component

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [x] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
