### ISSUE TITLE
Components: Explore monorepo with different framework libraries

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#295]
**TODO**
- [x] Build React library to test adding additional compatibility  to web components
- [x] Update GitHub actions 

**Outcomes**
- Gcds-components repo hosting multiple packages

**Deliverables**
- A component monorepo with support for multiple frameworks.

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
