### ISSUE TITLE
Utility framework: Research 

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#296]
**TODO**
- [x] Research what is currently available in WET as well as other utility frameworks
- [x] Look at different implementation options

**Outcomes**
- [x] Define the structure of the framework
- [x] Define what will be included in the first iteration

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
