### ISSUE TITLE
Naming components English and French

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#297]
**TODO**
- [x] Research
- [x] Document decisions that aren't obvious choices
- [ ] Review by @melaniebmn  

**Outcomes**
Bilingual names that work for: 
Icon
Stepper
Alert
Details (Accordion)
Form Validation

Review: 
I added an aria-label for each component type to inform screen reader users about the kind of alert they are getting. Right now I have this:
This is a critical alert.
This is an info alert.
This is a success alert.
This is a warning alert.
And for french:
Ceci est une alerte d'effacement.
Ceci est une alerte d'information.
Ceci est une alerte de succès.
Ceci est une alerte d'avertissement.

**Deliverables**

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by SmartMouthWords** [comment]
Background: 
Amy Morris
  17:31
Is Alert  the standard term?


Melanie Boeckmann
:snow_capped_mountain:  17:31
We can change the term 'stepper' if you think there is something better
17:31
From what I could see, design systems vary between alert and notification


Amy Morris
  17:32
Oh, that's what I was thinking: notification


Melanie Boeckmann
:snow_capped_mountain:  17:32
And then for the details component, we were originally going to call it accordion but Nick raised the good point that we are trying to stick to using the native HTML name whenever possible, so we named it details
:+1::skin-tone-2:
1

17:33
I think we should maybe add accordion in brackets behind the heading though because otherwise people might not know what it is
17:33
I can rename the component to notification if you like?
17:33
The PR is not merged yet
17:34
Sorry 3 conversations in one haha


Amy Morris
  17:34
ha – no worries
thank-you
merci-fleur
+1::skin-tone-2





17:36
I want to look at a couple examples for notification. I think the term notification is more widely understood as nudges on your device like banners and sounds
17:36
but I'm worried using Alerts will promote the current misuse of this component in the GC
17:36
It's very overused and wrongly used


Melanie Boeckmann
:snow_capped_mountain:  17:36
Makes sense! I can rename it, no big deal :slightly_smiling_face:
17:37
I'll keep the PR open for now and we can decide next week if you'd like to do some research first before making a call

**Comment by SmartMouthWords** [comment]
Will name the components as the documentation for each is reviewed in English and French.
