### ISSUE TITLE
Utility framework: Implementation

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#299]
**TODO**
Build utility framework, including the following properties
- [ ] typography utility classes
- [ ] flexbox utility classes
- [ ] grid utility classes
- [ ] spacing utility classes
- [ ] position utility classes
- [ ] general utility classes (images, icons, display, cursor, etc.)

**Outcomes**
- Gcds-utilities repo hosting the utility framework

**Deliverables**
- A utility framework with support for a variety of utility classes.

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
