### ISSUE TITLE
gcds-components: angular library

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#300]
**TODO**
- [ ] Add angular library to the gcds-components repo

**Outcomes**
- Provide flexibilty when using the gcds-components in an angualr app

**Deliverables**
- A new npm package `gcds-components-angular`

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
