### ISSUE TITLE
Add security.md, code_of_conduct.md, and contributing.md files to our repos

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#303]
**TODO**
- [x] Add security.md
- [x] Add code_of_conduct.md
- [x] Add contributing.md

**Outcomes**
- Files have been added to our repos.

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
