### ISSUE TITLE
EN Documentation: Icon component

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#304]
**TODO**
- [x]  First version of EN documentation for component using documentation template
- [ ]  Review of documentation
- [ ]  Publishing documentation on site

**Outcomes**
- First version of documentation for component for feedback

**Deliverables**
- Published documentation page(s)

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by SmartMouthWords** [comment]
Some notes from a past dev/design review where we'd discussed the use of descriptive text for icons. Some of the outstanding questions:
- How can a user determine if their icon is decorative only
- When should a user include descriptive text? Some icons have built in labels or descriptions and others don't, so how to avoid having a label + alt text being read out by AT while ensuring all icons are appropriately flagged for end users using assistive technology.
[https://docs.google.com/document/d/1azuCFDh3R4D0Qsz5N6S2Vxe2zxbgb2Qrb4aPgLCxtXc/edit](url)
