### ISSUE TITLE
EN Documentation: File Uploader component

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#305]
**TODO**
- [x]  First version of EN documentation for component using documentation template
- [ ]  Review of documentation
- [ ]  Publishing documentation on site

**Outcomes**
- First version of documentation for component for feedback

**Deliverables**
- Published documentation page(s)

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by melaniebmn** [comment]
@nmakuch can you review the design part, please?

@SmartMouthWords the draft is ready for your review.

The draft can be found here:
https://docs.google.com/document/d/108aAGeUxiRuHlDSgz7qC-9qWgiQypw1qC9bN4JJr3qQ/edit

**Comment by nmakuch** [comment]
Reviewed, not sure if Amy still has stuff to add
