### ISSUE TITLE
EN Documentation: Details component

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#307]
**TODO**
- [x]  First version of EN documentation for component using documentation template
- [ ]  Review of documentation
- [ ]  Publishing documentation on site

**Outcomes**
- First version of documentation for component for feedback

**Deliverables**
- Published documentation page(s)

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by melaniebmn** [comment]
@nmakuch can you review the design part, please?

@SmartMouthWords the draft is ready for your review.

The draft can be found here:
https://docs.google.com/document/d/1Pm017H_4eNOOv5f0HlzYPuLHo5dlb75OcbAFf2bgOEw/edit

**Comment by nmakuch** [comment]
Nothing to add currently
