### ISSUE TITLE
Utility framework - version 1.0.0

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#315]
**TODO**
- [ ] Get utility framework ready for version 1.0.0

**Outcomes**
- Version 1.0.0 of the utility framework

**Deliverables**
Framework including
- [x] Include Fonts with UF
- [x] Update package.json
- [x] Update readme (+ create general readme template)
- [ ] Breakpoint support
- [ ] Support for different states

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
