### ISSUE TITLE
FR Content: Utility Framework Readme

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#316]
**TODO**
- [ ] Create french translation for utility framework readme

**Outcomes**
- French content for utility framework readme

**Content**
The english content can be found here:
https://docs.google.com/document/d/1cUxHG55aidGuzJq32494XqvEDG7kkCDcOrBiSwpEY9c/edit#heading=h.p4mppd5kaujs

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
