### ISSUE TITLE
Update component props + classes to follow consistent naming

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#317]
**TODO**
- [ ] Update component props + classes to follow consistent naming

**Outcomes**
- Updated component props + classes following consistent naming

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
