### ISSUE TITLE
Update web components with updated Figma designs

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#318]
**TODO**
- [ ] Update web components based on updated Figma designs

**Outcomes**
- Synced Figma and web component designs

**Deliverables**
- Updated web components

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
