### ISSUE TITLE
Update package.json and readme.md files for gcds-tokens repo (EN)

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#321]
**TODO**
- [x] Update package.json and readme.md files for gcds-tokens repo

**Outcomes**
- Updated package.json and readme.md files

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic
