### ISSUE TITLE
Update Lang-Toggle and Buttons states to match figma designs

### ISSUE THREAD

**Issue by nmakuch** [cds-snc/design-gc-conception#376]
**CONTEXT**

Our language toggle and button states were updated a little while ago so they no longer match the states in our components repository.

Button states
- [View them in figma](https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/Canadian-Digital-Service%E2%80%A8---GC-Design-System?node-id=2319-7955&t=AwIiCGSLOD0jPlPn-0)

Language-toggle states
- [View them in figma](https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/Canadian-Digital-Service%E2%80%A8---GC-Design-System?node-id=1780-5094&t=AwIiCGSLOD0jPlPn-0)

**TODO**
- [x] Update lang toggle states
- [x] Update button states
- [x] Create tokens where necessary

**Outcomes**
- Styles are added to the components repo
- Tokens have been created in our tokens repo

**Deliverables**
- [Components PR#150](https://github.com/cds-snc/gcds-components/pull/150)
- [Tokens PR#113](https://github.com/cds-snc/gcds-tokens/pull/113)

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [x] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
