### ISSUE TITLE
Glossary + Workshop

### ISSUE THREAD

**Issue by mcman12** [cds-snc/design-gc-conception#68]
Organize team workshop to discuss common vocabulary so the development team is aligned on what each term means

**TODO**
- [x] Create board
- [x] Set time for workshop
- [x] Reorganize board
- [x] Group discussion
- [ ] Add agreed upon definitions to glossary  

**Outcomes**
- Shared understanding of common terminology used in the team
- Broaden team understanding of technical terms 
- Document terms in glossary to help inform onboarding documentation

**Deliverables**
- List of terms and definitions 
WIP: [https://docs.google.com/spreadsheets/d/1rrxi6nLkKmsP1QX5mSRGrArb4M-CjlNhfFQVR8Vqjz4/edit#gid=1038007303](url)
 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [x] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
- User onboarding
- Full glossary (documenting terms will be an ongoing effort)

**Comment by adeyfarah** [comment]
Common vocabulary - change to a epic @SmartMouthWords

**Comment by mcman12** [comment]
will run first with product pod next week.

**Comment by adeyfarah** [comment]
Mini workshop during POD sync (Tuesday)

**Comment by ioanacontu** [comment]
@SmartMouthWords Pulling in some of the results of the tech terms for component make-up into the glossary.

**Comment by ioanacontu** [comment]
Ongoing. Pausing this to focus on the other tasks.
