### ISSUE TITLE
Pattern Inventory - Colour

### ISSUE THREAD

**Issue by mcman12** [cds-snc/design-gc-conception#69]
**TODO**
- [ ] Analyze inventory from:
- Overview of the inventory of GCWeb design element: https://www.projectwallace.com/~delisma/gcweb/branding
- Recommendations for streamlining GCWeb design principles: https://www.figma.com/file/8189dLvqRAFIpPMbO32hbU/Foundations?node-id=0%3A1
- [ ] Clarify the use of the different colours
- [ ] Share insights with the team

**Outcomes**
- Colour library for the design tokens

**Deliverables**
- Documented list of colours and their specific use

**Out of scope**
- Typography (will be addressed in another card)
