### ISSUE TITLE
Preparation of GCWeb to allow design token integration

### ISSUE THREAD

**Issue by duboisp** [cds-snc/design-gc-conception#72]
**TODO**
* [x] Prepare a demo showing the current situation
* [x] Remove the double integration layer of wet-boew that import bootstrap3
* [x] Reorganize how SASS file are imported and override style. Ensure happen as expected and utility CSS are added at the end.
* [x] Group and identify override
   * [ ] For each: Clean up override
* [ ] Update the build script to automate the SASS integration
* [x] Perform a visual test of each components to ensure they still work as expected
   * [x] For each: Fix reported issue
* [ ] Validate and indicate where design token can be integrated

**Outcomes**
* Improved CSS integration in GCWeb which should reduce the size of the CSS file and unessary browser override
* Integration of design token without requiring to apply an override

**Deliverable**
* Intruction on how to integrate design token
* Removal of the double CSS framework interdependance (GCWeb -> wetboew and GCWeb -> Bootstrap)

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
* New style or dependancy upgrade
* Documentation of currently undocumented style

**Comment by duboisp** [comment]
## Démo

The following is the presenter notes

### 1. CSS Dependency

Currently: GCWeb -@import-> wet-boew -@import-> bootstrap
First mod: GCWeb -@import-> wet-boew -and- bootstrap

Keys files
* GCWeb - Main entry - https://github.com/wet-boew/GCWeb/blob/master/sites/theme.scss
* wet-boew - Bootstrap - https://github.com/wet-boew/wet-boew/blob/master/src/base/_bootstrap.scss
* Bootstrap - Main entry - https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/_bootstrap.scss
* wet-boew - Baseline and components - https://github.com/wet-boew/wet-boew/blob/master/src/base/_wet-boew.scss
* GCWeb - wet-boew overrides - https://github.com/wet-boew/GCWeb/blob/master/components/baseline/wet-boew-overrides.scss


### 2. Issue

Show the CSS rules override like `font-size` from the browser console
Any future change, like applying design token, will require an override, which slow down the performance of the website

### 3. GCWeb version 5

Explain the technical challenges

### 4. Overview of the proposed changes

### 5. Open discussion

**Comment by duboisp** [comment]
PR in wet-boew was approved and PR in GCWeb was submitted: https://github.com/wet-boew/GCWeb/pull/1897

We are initiating the testing today which will be coordinated by @GormFrank

**Comment by mcman12** [comment]
pr merged today

**Comment by duboisp** [comment]
Those update is not included in the latest version of GCWeb v10.0.1.

So when the design token will be ready, we would be able to experiment it also with GCWeb.

During this exercise, we can now use this file to easily find all the component included in GCWeb.: https://github.com/wet-boew/GCWeb/blob/master/sites/theme.scss
