### ISSUE TITLE
Update error summary link styling and anatomy image on figma

### ISSUE THREAD

**Issue by nmakuch** [cds-snc/design-gc-conception#723]
**TODO**
- [x] Update error summary links in figma to use global link styling
- [x] Update anatomy image in figma

**Outcomes**
- Image on the doc site will be the same as in figma library

**Deliverables**
- Doc site PR
- Anatomy image

**Estimated Effort**
- [x] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Comment by nmakuch** [comment]
<img width="1072" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkJoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a5392809cb95821f8dcc23e84a8d127b71d8d747/component%20%2B%20marker.svg" alt="component + marker.svg" />
