### ISSUE TITLE
Update error summary links to use link styles and update anatomy image

### ISSUE THREAD

**Issue by nmakuch** [cds-snc/design-gc-conception#755]
**TODO**
- [ ] Update error summary link styles 
- [ ] Update error summary anatomy images

**Outcomes**
- Error summary links should use link component if possible (visually should look the same)
- Update anatomy image on the docsite for the error summary component

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by adorayi** [comment]
Dependency on SSR work, ready for publishing.

**Comment by melaniebmn** [comment]
I received the new preview + anatomy images but I'm still missing the new alt-text description in English + french for the new anatomy images.

Here are the anatomy images that we need alt text for:

<img width="1102" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlp1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54ed15f96bd8113a3d611e22047ceff131a31f02/Screenshot%202024-04-17%20at%202.29.02%E2%80%AFPM.png" alt="Screenshot 2024-04-17 at 2.29.02 PM.png" />

<img width="1097" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmR1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3f3ac23519219af1ee31b0e33d6089c4669a0d5/Screenshot%202024-04-17%20at%202.29.08%E2%80%AFPM.png" alt="Screenshot 2024-04-17 at 2.29.08 PM.png" />

**Comment by melaniebmn** [comment]
@SmartMouthWords flagging you for the missing content - thank you!

**Comment by melaniebmn** [comment]
@SmartMouthWords this is the ticket for the error summary alt text

**Comment by SmartMouthWords** [comment]
Added error summary alt text in FR and EN.

**Comment by adorayi** [comment]
Hold off on this to release together with Wednesday 5/8 release.

**Comment by adorayi** [comment]
@melaniebmn please update this ticket to reflect the new decisions.

**Comment by melaniebmn** [comment]
Reversing the decision to use our default link styling for error summary links and going back to using the red error style instead. Here is the decision document for that decision:

https://docs.google.com/document/d/185seVPLzZr11b9lGjBieZolLp3XOk8Uedu4Pef7ucBA/edit

**Comment by melaniebmn** [comment]
@adorayi closing in favor of: https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/899
