### ISSUE TITLE
Present current draft work on tech agnostic and modular approach

### ISSUE THREAD

**Issue by mcman12** [cds-snc/design-gc-conception#76]
**TODO**
- [x] Prep presentation
- [x] Present at product pod
- [ ] Present at dev community?

**Outcomes**
- Common understanding of possibilities/approach
- generates questions from other team members

**Deliverables**
- recorded presentation
- light proof of concept

**Estimated Effort**
- [x] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
- actual workable end-to-end proof of concept

**Comment by adeyfarah** [comment]
Discussion/presentation in POD sync; estimated effort to be added after

**Comment by adeyfarah** [comment]
@ioana to follow up with Josh

**Comment by duboisp** [comment]
Example, see code sample at the middle to the end of this page: https://wet-boew.github.io/GCWeb/components/gc-features/gc-features-en.html

Also the public API for the semantic version, described in #42, are supporting the tech agnostic version illustrated by the component documentation.

The presentation has initiated discussion if we are leveraging existing product, like bootstrap 3 or starting from scratch.
