### ISSUE TITLE
Proof of concept for design tokens

### ISSUE THREAD

**Issue by mcman12** [cds-snc/design-gc-conception#77]
**TODO**
- [x] CommonJS module for the colour ramp
- [x] Read the W3C community [1st public editor's draft on design tokens](https://design-tokens.github.io/community-group/format/)
- [x] Custom JSON transform in Style Dictionary for exporting to Figma
- [x] Figma Tokens plug-in integration
- [ ] Build a web page
- [ ] Explore documentation/comments in token file

**Outcomes**
- Common understanding of how we can tackle design tokens

**Deliverables**
- presentation to the team
- poc

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
- typography, size, space, time, assets, motion, icons tokens.
- integration of design tokens into mobile platforms and other non-web frameworks.

**Comment by mcman12** [comment]
research and experimentation
- working on sync between web page and figma

**Comment by mcman12** [comment]
got custom format to work with figma. 
This week working on integrating it in central spot so that designers can change things in figma and dev can get output from github.

**Comment by duboisp** [comment]
For reference: the work that david is doing is here: https://github.com/cds-snc/gc-design-tokens
