### ISSUE TITLE
Setup alpha documentation site

### ISSUE THREAD

**Issue by mcman12** [cds-snc/design-gc-conception#78]
**TODO**
- [ ] Choose a git repo for it
- [ ] Choose a URL for the repo
- [x] Figuring the publishing workflow
- [x] Choose a CMS depending on the publishing workflow

**Outcomes**
- A proof of concept GitHub pages site to act as a playground for testing

**Deliverables**
- A setup GitHub repo with automated pushing to GitHub pages.

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
- fill it up with content

**Comment by adeyfarah** [comment]
Get update on Monday sync

**Comment by mcman12** [comment]
@ethanWallace to tackle publishing workflow
