### ISSUE TITLE
JTBD / User needs exercise

### ISSUE THREAD

**Issue by mcman12** [cds-snc/design-gc-conception#80]
**TODO**
- [x] Add Peter and Laura in zenhub
- [x] Prep the workshop
- [x] Run workshop
- [x] Wrap-up and next steps

**Outcomes**
- Identify potential research questions
- Categorize user needs by job stories
- Help team stay focus on what end users need to actually do when interacting with a DS

**Deliverables**
- List of jobs to be done to prioritize
- List research questions

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
- prioritize the JTBD
- evaluate with actual users

**Comment by CatalinaPerez123** [comment]
Nov. 8 - Workshop with Design system team to generate a list of specific needs / motivations for consulting the design system

**Comment by mcman12** [comment]
grouping in documents, would like to have feedback.

**Comment by CatalinaPerez123** [comment]
Summary of first exercise with the team. Will validate and update with community input https://miro.com/app/board/o9J_lkSA6hQ=/
