### ISSUE TITLE
Team Commitment Exercise

### ISSUE THREAD

**Issue by mcman12** [cds-snc/design-gc-conception#81]
**TODO**
- [ ] Prep board
- [ ] schedule a-sync time
- [ ] book session
- [ ] run session
- [ ] gather and share team commitments

**Outcomes**
- build trust amongst team members
- get to know each other better
- set clear team commitments to ensure collaboration moving forward

**Deliverables**
- trello board and demo at review

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [x] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-
