### ISSUE TITLE
Create a research repository for GCDS

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/design-gc-conception#827]
A research repository helps us to find stuff we already learned about, show gaps where we don't have research, and also help Platform-wide research.

## To-do
- [x] Outline the research ops process: [here](https://miro.com/app/board/uXjVKXmZtL4=/) (to test)
- [x] Test it out with an example research activity
- [x] Review past research and put into the repository (including DTO research)
- [x] Walkthrough with Luwam

## Definition of done 
- [x]  Team has awareness of the artifact and knows how to interact and what are the outcomes out of that 

## Reviewed process by

- [x] @samburtonCDS 
- [x] @Lu-stack-art 
- [ ] @ClementineHahn ?

**Comment by adriannelee** [comment]
- Finished organizing and skimming through DTO research
- Logged the research questions from the previous ‘Research Bank’ board and from the user journey map & product walkthroughs.
Doing today:
- Research ops: Set up a doc on OneDrive to document info on participants & consent
Review old research in more detail to see which questions we’ve already answered.

**Comment by adriannelee** [comment]
- Going through old research in more detail to see which questions have been answered.
- Synching with Luwam on the research ops process

**Comment by adriannelee** [comment]
- Reviewing the research repository with designers & Sam B today
- Going through old research in more detail to see which questions have been answered.

**Comment by adriannelee** [comment]
Reviewing A/B tests from across GC to add to repository today
