### ISSUE TITLE
v1. Site map 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/design-gc-conception#84]
**TODO**
- [x] Review initial user research research and developer interviews  
- [x] Draft site map, annotate with notes from research 
- [x] Share with Guidance Pod for feedback and iteration
- [ ] Share with Ethan for prototyping 

**Outcomes**
- Understand how many pages of content we will need for the v.1 Alpha documentation site 
- Understand how people enter the site 

**Deliverables**
- List of core actions 
- Site map (Figma file) 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [x] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
- Ideal state journey map

**Comment by samsadasivan** [comment]
@nmakuch  — leading

**Comment by samsadasivan** [comment]
Starting work here in this [figma file](https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/User-Journey-Maps?node-id=230%3A2): [focus] to lay out the pages we need to have for a GC web site and a MVP design system product

**Comment by adeyfarah** [comment]
@ethanWallace to send link to the alpha documentation

**Comment by ioanacontu** [comment]
Ongoing. More people will be added. Review at Guidance pod meeting on Wed at 11.am.
