### ISSUE TITLE
v1. Component page

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/design-gc-conception#85]
**TODO**
- [x] integrate sitemap into the alpha doc site
- [ ] Workshop draft and notes 
- [ ] Create initial wireframe draft for button page
- [ ] Bring wireframe to review

**Outcomes**
- Understand and curate the experience of someone interacting and learning about a component from the design system on the documentation site. 
- Share early for prototyping any interactions on the page. 

**Deliverables**
- Wireframe 
- Coded page (stretch)  

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-  TBD

**Comment by samsadasivan** [comment]
@samsadasivan — leading (for now)

**Comment by samsadasivan** [comment]
Pulling research from @CatalinaPerez123 https://miro.com/app/board/o9J_lkSA6hQ=/
to help inform design decisions

**Comment by ioanacontu** [comment]
On Tuesday @samsadasivan and @nmakuch to connect on this.

**Comment by jmealing** [comment]
@SmartMouthWords @nmakuch Can I also be invited to join your chat on Tuesday?

**Comment by SmartMouthWords** [comment]
A [WIP] content model for components that identifies the content objects (content chunks) for component pages: https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/Drafting-data?node-id=244%3A2

**Comment by samsadasivan** [comment]
Connected to the Figma integration work
