### ISSUE TITLE
v1. Design decision template 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/design-gc-conception#87]
**TODO**
- [ ] Draft a template in spreadsheets to log decisions based on some aspects of the current process  
- [ ] Share with the product and guidance pod  
- [ ] Refine
- [ ] Share with Ethan for prototyping  

**Outcomes**
- Understand what content/guidance is needed so that users can be informed in how decisions are made for the design system.
- Share a draft example early so that we can prototype how we log decisions around the design tokens (current decision in flux).

**Deliverables**
- Spreadsheet: draft categories of guidance   

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [X] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-  Decisions for the governance, all aspects of the documentation site 
- Not a template for all design decisions (hoping for an example of what design decisions could look like)

**Comment by samsadasivan** [comment]
@SmartMouthWords — leading

**Comment by duboisp** [comment]
For example, see the design decision in wet-boew here: https://wet-boew.github.io/wet-boew-documentation/decision/index-en.html

A design decision should have went through a rigid process which include and give time for each step to occur. Step like: "draft, peers review, community review, present, approval, current, appeal, withdraw..."

I suggest to keep those design decision in a registry where each decision will have its own and unique identifier. That none of them will be removed (unpublished) but kept online for historical purpose even if they are not accurate anymore. Something like how w3c proceed with their standard track or the [IETF ](https://www.ietf.org/) work for the publication of RCF documents
