### ISSUE TITLE
(HOLD) JS Prototype with isolated components (HTML. CSS, JS, data layer)

### ISSUE THREAD

**Issue by mcman12** [cds-snc/design-gc-conception#93]
## TODO
* [ ] Reproduce the IA structure (component based) similar to we the structure we experimented/tried with GCWeb.
* [ ] Create a working example

### Completed
* [x] Integrated community contribution + made adjustment as required (Jekyll template setup + CSS variable set)
* [x] Removed requireJS in favor of ES Module (import && export)
* [x] Added a Fetch option that allow load securely third party javascript in the page.
* [x] Updated all the working example to ensure they continue to work as expected

## Outcomes
- Generate discussion with the product pod
- Identify gaps and questions to discuss now, later

## Deliverables
- presentation at review

## Estimated Effort
* [ ] XS: 1 to 2 hours
* [ ] S: half a day
* [ ] M: 1-2 day
* [x] L: 1 week
* [x] XL: Move to an epic

## Out of scope
-

**Comment by mcman12** [comment]
discussion to happen before jumping into it during product pod

**Comment by duboisp** [comment]
Started from the existing work completed in wet-boew-experimental.
The following was done:
* Integrated community contribution + made adjustment as required (Jekyll template setup + CSS variable set)
* Removed requireJS in favor of ES Module (import && export)
* Added a Fetch option that allow load securely third party javascript in the page.
* Updated all the working example to ensure they continue to work as expected

Next:
* Reproduce the IA structure (component based) similar to we the structure we experimented/tried with GCWeb.
* Create a working example

**Comment by duboisp** [comment]
Here an example where we are polyfilling CSS stage 0 in browser
https://wet-boew.github.io/wet-boew-experimental/src/sites/wb.dev-css/example.html
