### ISSUE TITLE
Ensure all layers in FR figma are in FR

### ISSUE THREAD

**Issue by RavinaSamaroo** [cds-snc/design-gc-conception#936]
Some subcomponents were not translated to FR and therefore the layer is in EN in the FR library.

- e.g., button component's focus ring

- [x] Identify and document subcomponents that need translation
- [x] Send for translation
- [x] Apply and publish
