### ISSUE TITLE
Centralized documentation and decision log

### ISSUE THREAD

**Issue by mcman12** [cds-snc/design-gc-conception#97]
**TODO**
- [x] Identify location and structure for documents
- [x] Move Project Links there
- [x] Add decision log in project links google doc
- [ ] Ensure pods meeting have someone responsible for taking notes on decisions there

**Outcomes**
- Every documents for this project are in one organized spot
- Documents are easy to find
- We can decommission our notion page

**Deliverables**
- Demo at review

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by ioanacontu** [comment]
Mario and Adey met yesterday. A bit of work on card #94. Ongoing. 
Move to google sheets (from Notion).

**Comment by ioanacontu** [comment]
@ioanacontu to have a look at the Decisions log. 
Ongoing.

**Comment by ioanacontu** [comment]
Draft decision log: https://docs.google.com/spreadsheets/d/1tBWdpOENlKyCeOVmov8YmZTB-vEIqO-sC65yUD--GGo/edit
