### ISSUE TITLE
Start publishing the alpha documentation site 

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#99]
**TODO**
- [x] Publish repo to CDS-SNC GitHub org
- [x] Connect to Netlify
- [ ] Publish prototype Sitemap
- [ ] Publish v1 component page
- [x] Publish proof of concept end-to-end architecture component

**Outcomes**
- Have a space to test, interact and showcase different sprint deliverables

**Deliverables**
- Publish official GitHub repo: [Alpha design system documentation](https://github.com/cds-snc/alpha-design-system-documentation)
- GitHub site with deliverables from different sprint work items to showcase: [Alpha site](https://cds-snc.github.io/alpha-design-system-documentation/en/)

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [x] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
- TBD

**Comment by ioanacontu** [comment]
Heads-up: there will be some dependencies with other tasks.

**Comment by ioanacontu** [comment]
Ongoing.
